/*
 * Copyright 2024 Mosaic SoC Ltd. All rights reserved.
 * Authors: Luca Rufer, luca@mosaic-soc.com
 */

#ifndef __ARCHI_CHIPS_DORMOUSE_MEMORY_MAP_H__
#define __ARCHI_CHIPS_DORMOUSE_MEMORY_MAP_H__

#define ARCHI_L2_SHARED_ADDR 0x10000000
#define ARCHI_L2_SHARED_SIZE 0x01000000

#define ARCHI_DORMOUSE_BASE_ADDR 0x00000000
#define ARCHI_DORMOUSE_ADDR_RANGE 0x10000000
#define ARCHI_DORMOUSE_PERIPH_OFFSET 0x01000000
#define ARCHI_DORMOUSE_L1_OFFSET 0x04000000
#define ARCHI_DORMOUSE_DMEM_OFFSET 0x0C000000

#define ARCHI_L1_BANK_SIZE 0x00010000
#define ARCHI_DMEM_SIZE 0x00004000
#define ARCHI_BOOT_ROM_SIZE 0x00010000
#define ARCHI_IMEM_SIZE 0x00004000

#define ARCHI_L1_BANKS 2

/*
 * MEMORIES
 */

#define ARCHI_DORMOUSE_END_ADDR ( ARCHI_DORMOUSE_BASE_ADDR + ARCHI_DORMOUSE_ADDR_RANGE)

#define ARCHI_L1_ADDR       ( ARCHI_DORMOUSE_BASE_ADDR + ARCHI_DORMOUSE_L1_OFFSET )
#define ARCHI_DMEM_ADDR     ( ARCHI_DORMOUSE_BASE_ADDR + ARCHI_DORMOUSE_DMEM_OFFSET )
#define ARCHI_IMEM_ADDR     ( ARCHI_DORMOUSE_END_ADDR - ARCHI_IMEM_SIZE )
#define ARCHI_BOOT_ROM_ADDR ( ARCHI_IMEM_ADDR - ARCHI_BOOT_ROM_SIZE )

#define ARCHI_L1_BANK_ADDR(bank) (ARCHI_L1_ADDR + bank * ARCHI_L1_BANK_SIZE)

#define ARCHI_LOCAL_PRIV0_ADDR  ARCHI_L1_ADDR
#define ARCHI_LOCAL_PRIV0_SIZE  (ARCHI_L1_BANK_SIZE * ARCHI_L1_BANKS)

// L2 alias
#define ARCHI_L2_PRIV0_ADDR  ARCHI_L2_SHARED_ADDR
#define ARCHI_L2_PRIV0_SIZE  (ARCHI_L2_SHARED_SIZE / 2)

#define ARCHI_L2_PRIV1_ADDR  (ARCHI_L2_PRIV0_ADDR + ARCHI_L2_PRIV0_SIZE)
#define ARCHI_L2_PRIV1_SIZE  (ARCHI_L2_SHARED_SIZE / 2)

/*
 * PERIPHERALS
 */

#define ARCHI_DORMOUSE_PERIPHERALS_ADDR ( ARCHI_DORMOUSE_BASE_ADDR + ARCHI_DORMOUSE_PERIPH_OFFSET )

#define ARCHI_AON_PERIPHERALS_OFFSET 0x00000000
#define ARCHI_CLIC_OFFSET            0x01000000
#define ARCHI_BUS_ERR_OFFSET         0x01100000
#define ARCHI_SOC_CTRL_OFFSET        0x02000000
#define ARCHI_FC_TIMER_OFFSET        0x02001000
#define ARCHI_STDOUT_OFFSET          0x02FF0000

// Strides for core-specific peripherals
#define ARCHI_CLIC_STRIDE            0x00010000
#define ARCHI_BUS_ERR_STRIDE         0x00000030

// Clic Offset
#define ARCHI_CORE_CLIC_OFFSET(core) ( ARCHI_CLIC_OFFSET + ((core) * ARCHI_CLIC_STRIDE) )

// Bus Error offsets
#define ARCHI_INSTR_ERR_OFFSET(core)  ( ARCHI_BUS_ERR_OFFSET + ((core) * ARCHI_BUS_ERR_STRIDE) + 0x00000000 )
#define ARCHI_DATA_ERR_OFFSET(core)   ( ARCHI_BUS_ERR_OFFSET + ((core) * ARCHI_BUS_ERR_STRIDE) + 0x00000010 )
#define ARCHI_SHADOW_ERR_OFFSET(core) ( ARCHI_BUS_ERR_OFFSET + ((core) * ARCHI_BUS_ERR_STRIDE) + 0x00000020 )


#define ARCHI_AON_PERIPHERALS_ADDR  ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_AON_PERIPHERALS_OFFSET)
#define ARCHI_CLIC_ADDR(core)       ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_CORE_CLIC_OFFSET(core) )
#define ARCHI_INSTR_ERR_ADDR(core)  ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_INSTR_ERR_OFFSET(core) )
#define ARCHI_DATA_ERR_ADDR(core)   ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_DATA_ERR_OFFSET(core) )
#define ARCHI_SHADOW_ERR_ADDR(core) ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_SHADOW_ERR_OFFSET(core) )
#define ARCHI_SOC_CTRL_ADDR         ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_SOC_CTRL_OFFSET )
#define ARCHI_FC_TIMER_ADDR         ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_FC_TIMER_OFFSET )
#define ARCHI_STDOUT_ADDR           ( ARCHI_DORMOUSE_PERIPHERALS_ADDR + ARCHI_STDOUT_OFFSET )

#define ARCHI_AON_SOC_CTRL_OFFSET   0x00000000

#define ARCHI_AON_SOC_CTRL_ADDR     ( ARCHI_AON_PERIPHERALS_ADDR + ARCHI_AON_SOC_CTRL_OFFSET )

#define ARCHI_FC_TIMER_SIZE            0x00000800

#endif /* __ARCHI_CHIPS_DORMOUSE_MEMORY_MAP_H__ */
